### ISSUE TITLE
Other automatisms

### ISSUE THREAD

**Issue by sedrubal** [j4velin/WiFi-Automatic#11]
Hi,

I think, this is a very useful app, thank you ;)

Maybe you want to add other automatisms, like switch into silent mode, when disconnecting from Wi-Fi (leaving home) or turning on /off mobile data, when disconnecting/connecting to Wi-Fi and so on...

**Comment by crirus** [comment]
Any chance to add a feature that also prevent data usage while app turns wifi off and only enable if wifi connection fail?

The idea is to just stop wasting battery with any data transfer between intervals I set in app.

That will make the app full.
Thank you

**Comment by j4velin** [comment]
Feel free to fork the project, but I haven't planned to add a "mobile data" off function for this app
