### ISSUE TITLE
[FR] Extend range for screen off delay

### ISSUE THREAD

**Issue by ChristianTacke** [j4velin/WiFi-Automatic#12]
Thanks for this app!

When the screen is off/locked, the maximum time to wait until disabling wifi is one hour. On the one side, I want my phone to disable wifi, if I don't use it for an extended time. On the other hand, I use my phone as a "new mail reminder", so its wifi should be enabled for a reasonable time. And one hour is just a bit too short. Two hours or maybe three would be perfect, I think.

So could you please extend the allowed range to maybe 5 or 6 hours? Maybe even 12 hours. I really don't know.

I don't know, if the chooser can be filled with only useful entries, if so, I'd recommend to not use every minute starting from 30 minutes. Maybe …, 29, 30, 35, 40, 45, 50, 55, 60, 70, 80, 90, 100, 110, 120, 150, 180, 210, 240, 270, 300 would be good options? The number entry keypad can still be used to enter more detailed values?

**Comment by j4velin** [comment]
Sorry, but I dont think it makes much sense to turn the WiFi off only if the display has been off for 12 hours....
