### ISSUE TITLE
prefer "on AC power" over "screen off" option

### ISSUE THREAD

**Issue by ildar** [j4velin/WiFi-Automatic#13]
I am not 100% sure but think that when on AC power AND screen is off for the defined interval the WiFi is turned off.
I'd prefer that the "screen off" option work only when on Battery power. Agree?

**Comment by j4velin** [comment]
the "turn on wifi when connected to AC" turns on wifi, when connecting to a power source. the "turn off wifi when display is off for 10 mins" turns wifi off when the display is off for 10 minutes. So if you connect your device to a power source, it will turn on wifi, and it will turn it off after 10 mins of display off if you also enabled that option. the app does not have any option to ignore one rule when another one is active or something like that

**Comment by ildar** [comment]
then can we have "Do not turn off / or even Keep on when on AC power?
Thanks!
>
>

**Comment by j4velin** [comment]
Sorry, I haven't planned to implement any more complex priority setting or something like that in the Play Store version of the app, but feel free to fork the project

**Comment by ildar** [comment]
The app is great even in current state. Thanks for it.
