### ISSUE TITLE
Make play-services optional

### ISSUE THREAD

**Issue by krt16s** [j4velin/WiFi-Automatic#14]
Google's play-services are non-free software, thus your recent changes break the build for f-droid, a free/libre/open-source app repository. Could you provide a "full floss" build flavor, switch to a free replacement (when available?) or make it easy to strip (even when functionality gets lost)?

**Comment by j4velin** [comment]
I see what I can do about it

**Comment by j4velin** [comment]
Please let me know if that works: https://github.com/j4velin/WiFi-Automatic/commit/a490f82eb1ac680eca104817d0a28e4fad159a0b

**Comment by krt16s** [comment]
I think you meant to only switch play-services to `playCompile`, leaving the all other dependencies `compile`. 

Also note that ef8b647c33129901fca431bc8dcf1f3728108aa1 redid changes from 9a70fb8ceaa414b1dc5152d17a5ded19d1741931 which was reverted on purpose: See https://github.com/j4velin/WiFi-Automatic/issues/10 for details.

**Comment by j4velin** [comment]
Actually, all of the dependencies are only required with the new locations feature and its UI. Fixed the build file things in commit https://github.com/j4velin/WiFi-Automatic/commit/2cebf830d6ee4ed524bd390bd57fcd21bcd9e4ec

**Comment by krt16s** [comment]
Thanks for the quick fix, works fine here.
