### ISSUE TITLE
Postpone automatic switch-off if tablet is used

### ISSUE THREAD

**Issue by j-ed** [j4velin/WiFi-Automatic#15]
The last time I used my tablet exactly at the time for which the configured automatic switch-off should take place and Wifi was disabled. Would it be possible to automatically recognize if a tablet is currently used and postpone the switch-off event for e.g. 15-30min?

**Comment by j4velin** [comment]
I guess that can be seen as a similiar request as https://github.com/j4velin/WiFi-Automatic/issues/19
