### ISSUE TITLE
Mark location based Wifi switch-on as "in-app-buyable"

### ISSUE THREAD

**Issue by j-ed** [j4velin/WiFi-Automatic#16]
As I last started the app I realized that there was a new function which allows to switch on Wifi based on configured places. Unfortunately this function was grayed-out and no information was shown that this is only available after it has been enabled by an in-app-buy.
Would it be possible that optional functions which need to be paid for are marked as in-app-buyable?

**Comment by j4velin** [comment]
Actually, that option is greyed out only on devices which don't have a cell
radio and there can not use cell information for location determination

j-ed <notifications@github.com> schrieb am Do., 30. Apr. 2015 15:22:
