### ISSUE TITLE
Possibly causes DataStats app to stop functioning

### ISSUE THREAD

**Issue by Gitoffthelawn** [j4velin/WiFi-Automatic#17]
Hopefully not too many (or any) people have read my initial versions of this Issue post.  I've updated it to provide more details.

Here's the issue in a nutshell: I have used DataStats ( https://github.com/takke/DataStats ) for quite a while without a single issue.  I then installed WiFi-Automatic.  After installing WiFi-Automatic, DataStats would no longer work after I turned the screen off, waited just a few seconds, and then turned it back on.  DataStats would see no data after turning the screen back on.

I figured it was probably an app conflict, so I uninstalled WiFi-Automatic expecting DataStats to start working again.  Even after rebooting, DataStats works great until the screen is turned off; once the screen is turned off and then back on, it no longer shows throughput stats.  Reinstalling DataStats does not help.

So the big question: is it possible that WiFi-Automatic has changed something that would persist after being uninstalled?

I looked through my logs to try to determine if it could be something else.  I had updated a couple apps, but I took a close look at those, and I highly doubt there could be any relationship to this issue.

The only other thing that I did was run (it was already installated) and then uninstall Wifi Key Recovery ( https://github.com/alt236/Wifi-Key-Recovery---Android ).  It had root privs, but it should be read-only.

Since running WiFi-Automatic, I can't get DataStats to survive a screen off/on cycle.  As such, I am now limited in the testing I can provide.  Perhaps others can try the following to see if it reproduces the issue:

Steps I took:
1. Install DataStats ( https://github.com/takke/DataStats )
2. Set DataStats to auto start on boot
3. Reboot*
4. Install WiFi-Automatic ( https://github.com/j4velin/WiFi-Automatic )
5. Reboot
6. Let system stabilize after boot
6. Turn off screen
7. Wait a few seconds
8. Turn on screen
9. DataStats is now frozen at whatever level it was displaying when screen turned off

* I had updated a couple apps and ran then uninstalled Wifi Key Recovery at this step.

**Comment by j4velin** [comment]
I don't really think this is an issue of WiFi Automatic - the app only turns WiFi on or off. If another app stops working because WiFi has been turned off, then thats an issue of this other app

**Comment by Gitoffthelawn** [comment]
Thanks.  I appreciate your feedback.  Does WiFi Automatic change anything that could persist after it is uninstalled?

**Comment by j4velin** [comment]
Nope

**Comment by Gitoffthelawn** [comment]
That's good news.  Thanks!
