### ISSUE TITLE
Multiuser support

### ISSUE THREAD

**Issue by patrickhusi** [j4velin/WiFi-Automatic#21]
Hi everybody

Thanks for your great app.

I've installed this app on my multi user tablet for a single user. WiFi Automatic is configured to turn WiFi off when the screen is off for five minutes and turn WiFi on when unlocking the device.

Consider the following scenario misbehaving:
- User 1 with installed WiFi Automatic does anything
- User 1 locks the screen (means, that WiFi will be turned off in 5 minutes)
- User 2 without installed WiFi Automatic, unlocks de device
- After 5 minutes WiFi will be turned off

I think, the app should be able to work with multiple user accounts. 

Thank you
Patrick

**Comment by j4velin** [comment]
Well, the app doesn't get notified if User 2 unlocks the device, as the app is not installed for User 2 so there isn't much I can do about it actually
