### ISSUE TITLE
feature request: stop switching on during a period of time

### ISSUE THREAD

**Issue by derStephan** [j4velin/WiFi-Automatic#30]
I recently installed WiFi-Automatic on my Wileyfox Swift, running CyanogenMod 13. 

These are my settings (they are translated from German):

Switch on: 
- daily at 7:00 am
- every 1 hours
- during charging

Switch off: 
- if no network is within reach
- daily at 10:00 pm

Everything works fine except for switching off at 10:00 pm. Even if I switch it off by myself, it is switched on again to connect to my home network. 

It looks like it is still switching on every hour even between 10:00 pm and 7:00 am to look for known networks? 

May I ask to add a feature to set a time span when wireless is never automatically switched on?

Thanks in advance.

**Comment by j4velin** [comment]
Well, if you set the app to turn WiFi on every hour, it will turn WiFi on every hour. Even between 10.00 pm and 7.00 am
