### ISSUE TITLE
switch off at certain time does not work

### ISSUE THREAD

**Issue by derStephan** [j4velin/WiFi-Automatic#31]
Hi,

wifi automatic does not switch my wifi off at the set time. 

I am running cyanogenMod on a Wileyfox Swift. These are my settings (they are translated from German):

Switch on:
- daily at 7:00 am
- during charging

Switch off:
- if no network is within reach
- daily at 10:00 pm

Regards
Stephan

**Comment by j4velin** [comment]
Try the debug version (https://j4velin.de/debug/) and upload the log if the issue persists

**Comment by derStephan** [comment]
Sorry but I did not wait 11 months. I am using [Wi-Fi Matic](https://f-droid.org/repository/browse/?fdid=org.cprados.wificellmanager) now. I am happy with it. And it has the feature I asked for (#30). 

Thanks anyway.
