### ISSUE TITLE
Release 1.7.4

### ISSUE THREAD

**Issue by dimqua** [j4velin/WiFi-Automatic#36]
Please release the source code of the latest version available.

**Comment by j4velin** [comment]
The latest source code is already shown here on the master branch

**Comment by ildar** [comment]
I guess he asks to tag. E.g. F-Droid uses tags to identify newer versions
available.

**Comment by dimqua** [comment]
Yes, @ildar is right. 1.7.4 tag is missing, that's why f-droid version of the app is outdated.
