### ISSUE TITLE
Let the app run in background and prevent taskmanager from killing it

### ISSUE THREAD

**Issue by H34dl3ss** [j4velin/WiFi-Automatic#53]
This app is running fine on a MIUI 11 device, but when choosing to close all apps in task manager, it will also be closed. 
Although I toggeled autostart ON and removed energy saving policies, it will not restart and subsequently the WiFi won't switch as intended.
It should run in background without task manager being able to kill the process.
Maybe an icon in the toolbar to show the service status is a good idea also?

**Comment by j4velin** [comment]
If you dont want the app to be killed, then dont kill it in the task killer (or better: dont use task killers on Android). The app can not prevent it from being killed by another app
