### ISSUE TITLE
Disabling Wifi no longer working with target SDK 29

### ISSUE THREAD

**Issue by sanderbos** [j4velin/WiFi-Automatic#54]
Wifi Automatic is no longer working for me, since a few weeks Wifi is not disabled anymore after one hour of being outside of Wifi range (this is the setting I use).
This is on a OnePlus 6 phone running Android 10 (there have been no recent updates on the phone).

Since WiFi automatic is open source I compiled it myself (with some difficulty, because I am not an Android developer).

It is caused by
  uses-sdk android:targetSdkVersion="29"
in the manifest file, if I change it back to 28 it works again for me. (there were so few changes that this was the only real candidate)

https://developer.android.com/reference/android/net/wifi/WifiManager#setWifiEnabled(boolean)
seems to suggest that indeed something was changed with API level 29 in that method. Is it still working for you (can Wifi be disabled by the app on your phone?)?

I attached some captured matlog:
[2021-04-22-18-28-18.txt](https://github.com/j4velin/WiFi-Automatic/files/6359927/2021-04-22-18-28-18.txt)
I guess the only relevant lines are:
04-22 18:27:33.369 I/WifiService(1302): setWifiEnabled not allowed for uid=10462
04-22 18:27:33.383 D/WiFi-Automatic(15741): Unable to change WiFi state

**Comment by sanderbos** [comment]
(Side note: Could you change to classpath 'com.android.tools.build:gradle:3.5.4' or something like that in your build .gradle, as a non-Android developer I had so much trouble getting it to compile...)

**Comment by j4velin** [comment]
Yes, unfortunately that is true (Google issue tracker: https://issuetracker.google.com/issues/128554616). The app will no longer work when the target SDK is set to 29 or above - however, to be able to update the app in the Google Play Store, it requires at least target SDK 29 at the moment... So I guess I'll keep the "old" version on Google Play for now and you'd need to use F-Droid for any further updates (if there are any)

**Comment by sanderbos** [comment]
I updated the app from Google Play and indeed it's working again.
Thanks.
Sorry to hear that Google decided to break your app...
